version: '3'

services:
  client:
    container_name: client
    image: curlimages/curl
    command: tail -F /dev/stdout

  egress-gateway:
    container_name: egress
    image: envoyproxy/envoy:v1.21.0
    volumes:
    - ./gateway/envoy-ca-cert.pem:/etc/pki/CA/envoy-ca-cert.pem
    - ./gateway/envoy-cert.pem:/etc/pki/tls/certs/envoy-cert.pem
    - ./gateway/envoy-key.pem:/etc/pki/tls/private/envoy-key.pem
    - ./gateway/access.log:/var/log/envoy/access.log
    - ./gateway/${LISTENER_TYPE}/envoy.yaml:/etc/envoy/envoy.yaml

  external-proxy:
    container_name: proxy
    image: envoyproxy/envoy:v1.21.0
    volumes:
    - ./proxy/access.log:/var/log/envoy/access.log
    - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml
    - ./proxy/envoy-ca-cert.pem:/etc/pki/CA/envoy-ca-cert.pem
    - ./proxy/envoy-cert.pem:/etc/pki/tls/certs/envoy-cert.pem
    - ./proxy/envoy-key.pem:/etc/pki/tls/private/envoy-key.pem
