version: '3'

services:

  gateway:
    container_name: gateway
    image: envoyproxy/envoy:v1.29.0
    volumes:
    - ./gateway.yaml:/etc/envoy/envoy.yaml
    - ./gateway.local.crt:/etc/pki/tls/certs/gateway.local.crt
    - ./gateway.local.key:/etc/pki/tls/private/gateway.local.key
    - ./root-ca.crt:/etc/pki/tls/certs/root-ca.crt
    ports:
      - "8443:8443"
    depends_on:
    - server

  server:
    container_name: server
    image: kong/httpbin
    command: "gunicorn -b 0.0.0.0:8000 httpbin:app -k gevent"
