version: '3'

services:
  client:
    container_name: client
    image: curlimages/curl
    command: sleep infinity

  dynamic-forward-proxy:
    container_name: dynamic-proxy
    image: envoyproxy/envoy:v1.21.0
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml
    - ./root-ca.crt:/etc/pki/CA/envoy-ca-cert.pem
    - ./dynamic-proxy.crt:/etc/pki/tls/certs/envoy-cert.pem
    - ./dynamic-proxy.key:/etc/pki/tls/private/envoy-key.pem
